import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrainsMono= JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jetBrainsMono.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
